import { prisma } from "@/lib/db";
import { decryptConfig } from "@/lib/integrations/mask";
import { getCheckConnector } from "@/lib/integrations/checks";
import type { ProbeResult } from "@/lib/integrations/types";
import { computeValidUntil } from "@/lib/evidence";

export type CheckRunResult = {
  ran: number;
  passed: number;
  failed: number;
  errored: number;
  evidenceCreated: number;
  poamsOpened: number;
};

const FREQUENCY_MS: Record<string, number> = {
  HOURLY: 60 * 60 * 1000,
  DAILY: 24 * 60 * 60 * 1000,
  WEEKLY: 7 * 24 * 60 * 60 * 1000,
};
const FREQUENCY_CADENCE_DAYS: Record<string, number> = { HOURLY: 1, DAILY: 2, WEEKLY: 8 };

type MappedControl = { framework: string; controlId: string };

function parseMapped(json: string): MappedControl[] {
  try {
    const v = JSON.parse(json);
    return Array.isArray(v) ? (v as MappedControl[]) : [];
  } catch {
    return [];
  }
}

/**
 * Run continuous-controls-monitoring checks for an org. Each enabled assignment probes its external
 * integration, appends a CheckResult, writes an auto-evidence artifact linked to the mapped
 * controls, and opens/auto-resolves a POA&M on failure. Idempotent and isolated per assignment
 * (a probe error becomes status ERROR — it never aborts the whole run).
 */
export async function runChecks(orgId: string, opts: { due?: boolean } = {}): Promise<CheckRunResult> {
  const now = new Date();
  const assignments = await prisma.checkAssignment.findMany({
    where: { orgId, enabled: true },
    include: {
      check: true,
      system: { select: { id: true, name: true } },
      results: { orderBy: { checkedAt: "desc" }, take: 1 },
    },
  });

  const result: CheckRunResult = { ran: 0, passed: 0, failed: 0, errored: 0, evidenceCreated: 0, poamsOpened: 0 };

  for (const a of assignments) {
    // Honor frequency when running on a schedule.
    if (opts.due) {
      const last = a.results[0]?.checkedAt?.getTime() ?? 0;
      const interval = FREQUENCY_MS[a.check.frequency] ?? FREQUENCY_MS.DAILY;
      if (now.getTime() - last < interval) continue;
    }

    const connector = getCheckConnector(a.check.providerType);
    const integration = a.integrationId
      ? await prisma.integration.findFirst({ where: { id: a.integrationId, orgId }, select: { config: true } })
      : null;

    let probeResult: ProbeResult;
    try {
      const probe = connector?.probes[a.check.probe];
      if (!connector || !probe) throw new Error(`No connector/probe for ${a.check.providerType}.${a.check.probe}`);
      const config = integration ? decryptConfig(integration.config) : { mock: true };
      const params = JSON.parse(a.paramsJson || "{}");
      probeResult = await probe(config, params);
    } catch (e) {
      probeResult = { status: "ERROR", details: e instanceof Error ? e.message : "Probe error", evidence: {} };
    }

    result.ran++;
    if (probeResult.status === "PASS") result.passed++;
    else if (probeResult.status === "FAIL") result.failed++;
    else result.errored++;

    const dedupeKey = `checks:${a.systemId}:${a.check.key}`;
    const mapped = parseMapped(a.check.mappedControls);

    // Resolve the mapped controls that actually exist as implementations on this system.
    const implMatches = mapped.length
      ? await prisma.controlImplementation.findMany({
          where: {
            systemId: a.systemId,
            control: { OR: mapped.map((m) => ({ framework: m.framework, controlId: m.controlId })) },
          },
          select: { id: true },
        })
      : [];

    // --- Auto-evidence (skip on ERROR — nothing meaningful to attest) ---
    let evidenceId: string | null = null;
    if (probeResult.status !== "ERROR") {
      const cadenceDays = FREQUENCY_CADENCE_DAYS[a.check.frequency] ?? 2;
      const ev = await prisma.evidence.create({
        data: {
          systemId: a.systemId,
          title: `${a.check.title} — automated check (${probeResult.status})`,
          type: a.check.evidenceType,
          note: probeResult.details,
          uploadedById: null,
          approvalStatus: "APPROVED",
          collectedAt: now,
          cadenceDays,
          validUntil: computeValidUntil(now, cadenceDays),
          reviewedAt: now,
          reviewNote: "System-generated by continuous controls monitoring.",
          statusHistory: { create: { status: "APPROVED", note: "Automated check result.", changedBy: null } },
          links: { create: implMatches.map((i) => ({ implementationId: i.id })) },
        },
        select: { id: true },
      });
      evidenceId = ev.id;
      result.evidenceCreated++;
    }

    // --- POA&M open/auto-resolve ---
    const poamNumber = `CCM-${a.check.key}`;
    const existingPoam = await prisma.poam.findFirst({
      where: { systemId: a.systemId, poamNumber },
      select: { id: true, status: true },
    });
    let poamId: string | null = existingPoam?.id ?? null;

    if (probeResult.status === "FAIL") {
      if (!existingPoam) {
        const created = await prisma.poam.create({
          data: {
            poamNumber,
            systemId: a.systemId,
            weaknessTitle: `${a.check.title} failed`,
            weaknessDescription: probeResult.details,
            source: "ContinuousMonitoring",
            severity: a.check.severity,
            riskRating: a.check.severity,
            status: "OPEN",
            remediationPlan: a.check.remediation,
            implementationId: implMatches[0]?.id ?? null,
            statusHistory: { create: { status: "OPEN", note: "Opened by continuous controls monitoring.", changedBy: null } },
          },
          select: { id: true },
        });
        poamId = created.id;
        result.poamsOpened++;
      } else if (!["COMPLETED", "CLOSED"].includes(existingPoam.status)) {
        await prisma.poam.update({ where: { id: existingPoam.id }, data: { weaknessDescription: probeResult.details } });
      } else {
        // Previously resolved but failing again — reopen.
        await prisma.poam.update({
          where: { id: existingPoam.id },
          data: { status: "OPEN", weaknessDescription: probeResult.details, statusHistory: { create: { status: "OPEN", note: "Reopened: check failing again.", changedBy: null } } },
        });
      }
    } else if (probeResult.status === "PASS" && existingPoam && !["COMPLETED", "CLOSED"].includes(existingPoam.status)) {
      await prisma.poam.update({
        where: { id: existingPoam.id },
        data: { status: "COMPLETED", actualCompletion: now, statusHistory: { create: { status: "COMPLETED", note: "Auto-resolved: check now passing.", changedBy: null } } },
      });
    }

    await prisma.checkResult.create({
      data: {
        orgId,
        systemId: a.systemId,
        assignmentId: a.id,
        status: probeResult.status,
        details: probeResult.details,
        evidenceJson: JSON.stringify(probeResult.evidence ?? {}),
        resourceCount: probeResult.resourceCount ?? 0,
        failingCount: probeResult.failingCount ?? 0,
        dedupeKey,
        evidenceId,
        poamId,
      },
    });
  }

  return result;
}
